struct vehicle_status_
{
	unsigned long long timestamp;
	unsigned long system_id;
	unsigned long component_id;
	unsigned long onboard_control_sensors_present;
	unsigned long onboard_control_sensors_enabled;
	unsigned long onboard_control_sensors_health;
	octet nav_state;
	octet arming_state;
	octet hil_state;
	boolean failsafe;
	octet system_type;
	boolean is_rotary_wing;
	boolean is_vtol;
	boolean vtol_fw_permanent_stab;
	boolean in_transition_mode;
	boolean in_transition_to_fw;
	boolean rc_signal_lost;
	octet rc_input_mode;
	boolean data_link_lost;
	octet data_link_lost_counter;
	boolean engine_failure;
	boolean engine_failure_cmd;
	boolean mission_failure;

}; // struct vehicle_status_
